"""
backend/app/catalyst/smartbrowz.py
=====================================
KSP Crime Intelligence Platform — Catalyst SmartBrowz Wrapper

Wraps the Zoho Catalyst SmartBrowz service for headless browser operations.

Used for generating
-------------------
  * Investigation Report PDFs (Markdown → HTML → PDF via SmartBrowz)
  * Case Summary PDFs
  * Crime Chart images (chart rendered HTML → PNG)
  * Evidence bundle PDFs
  * FIR Print-ready PDFs

How it works
------------
  1. The report service generates HTML content (using Jinja2 or f-strings)
  2. SmartBrowz renders the HTML in a headless browser
  3. The resulting PDF/PNG bytes are returned
  4. The caller uploads the result to Catalyst File Store

Environment variables
---------------------
  No additional vars required beyond CATALYST_PROJECT_ID / CATALYST_PROJECT_KEY.
  SmartBrowz is a project-level service with no separate token.

PDF options reference
---------------------
  format:       "A4" | "Letter"
  orientation:  "portrait" | "landscape"
  margin_top:   CSS string e.g. "20mm"
  margin_bottom: CSS string
  header_html:  HTML string for page header
  footer_html:  HTML string with page number
"""
from __future__ import annotations

import logging
from typing import Any, Dict, Optional

from app.catalyst.config import CatalystServiceError, get_catalyst_app, is_catalyst_available

logger = logging.getLogger("ksp.catalyst.smartbrowz")

# Default PDF generation options
DEFAULT_PDF_OPTIONS: Dict[str, Any] = {
    "format": "A4",
    "orientation": "portrait",
    "margin_top": "15mm",
    "margin_bottom": "15mm",
    "margin_left": "15mm",
    "margin_right": "15mm",
    "print_background": True,
}

# KSP letterhead HTML template injected into all reports
KSP_HEADER_HTML = """
<div style="font-family: Arial, sans-serif; font-size: 10px; text-align: center;
            border-bottom: 1px solid #333; padding-bottom: 4px; width: 100%;">
  <strong>Karnataka State Police — Confidential</strong>
  &nbsp;|&nbsp; Generated by KSP Crime Intelligence Platform
</div>
"""

KSP_FOOTER_HTML = """
<div style="font-family: Arial, sans-serif; font-size: 9px; color: #666;
            text-align: center; width: 100%;">
  Page <span class="pageNumber"></span> of <span class="totalPages"></span>
  &nbsp;|&nbsp; CONFIDENTIAL — FOR OFFICIAL USE ONLY
</div>
"""


class CatalystSmartBrowzWrapper:
    """
    Thin wrapper around Catalyst SmartBrowz headless browser service.

    Generates PDF and screenshot bytes from HTML content.
    """

    # ── PDF generation ─────────────────────────────────────────────────────

    def generate_pdf(
        self,
        html_content: str,
        options: Optional[Dict[str, Any]] = None,
        include_ksp_letterhead: bool = True,
    ) -> bytes:
        """
        Render HTML content as a PDF document.

        Parameters
        ----------
        html_content:
            Full HTML string to render.  Should include ``<html>``, ``<head>``,
            ``<body>`` tags and embedded CSS for accurate rendering.
        options:
            PDF rendering options (overrides ``DEFAULT_PDF_OPTIONS``).
            Supported keys: format, orientation, margin_*, print_background.
        include_ksp_letterhead:
            If True, injects KSP header and page-number footer automatically.

        Returns
        -------
        bytes
            PDF bytes on success.  Empty bytes if SmartBrowz is unavailable.

        Raises
        ------
        CatalystServiceError
            If Catalyst is configured but SmartBrowz returns an error.
        """
        if not is_catalyst_available():
            logger.warning(
                "Catalyst unavailable — SmartBrowz PDF generation skipped.  "
                "Returning empty bytes."
            )
            return b""

        try:
            app = get_catalyst_app()
            smart_browz = app.SmartBrowz()  # type: ignore[attr-defined]

            merged_options = {**DEFAULT_PDF_OPTIONS, **(options or {})}

            if include_ksp_letterhead:
                merged_options["header_template"] = KSP_HEADER_HTML
                merged_options["footer_template"] = KSP_FOOTER_HTML

            pdf_bytes = smart_browz.generate_pdf(html_content, merged_options)

            logger.info(
                "SmartBrowz PDF generated: %d bytes (html_len=%d)",
                len(pdf_bytes),
                len(html_content),
            )
            return pdf_bytes if pdf_bytes else b""
        except Exception as exc:
            logger.error("SmartBrowz generate_pdf failed: %s", exc)
            raise CatalystServiceError(f"SmartBrowz PDF generation failed: {exc}") from exc

    # ── Screenshot generation ──────────────────────────────────────────────

    def generate_screenshot(
        self,
        url: Optional[str] = None,
        html_content: Optional[str] = None,
        width: int = 1280,
        height: int = 720,
        full_page: bool = True,
    ) -> bytes:
        """
        Capture a screenshot of a URL or HTML content.

        Used for crime chart images and dashboard snapshots.

        Parameters
        ----------
        url:
            Public URL to screenshot (mutually exclusive with html_content).
        html_content:
            HTML string to render and screenshot.
        width:
            Viewport width in pixels.
        height:
            Viewport height in pixels.
        full_page:
            If True, capture the full scrollable page height.

        Returns
        -------
        bytes
            PNG image bytes.
        """
        if not is_catalyst_available():
            logger.warning("Catalyst unavailable — SmartBrowz screenshot skipped")
            return b""

        if not url and not html_content:
            raise ValueError("Either url or html_content must be provided")

        try:
            app = get_catalyst_app()
            smart_browz = app.SmartBrowz()  # type: ignore[attr-defined]

            options = {
                "viewport_width": width,
                "viewport_height": height,
                "full_page": full_page,
                "format": "png",
            }

            if url:
                screenshot_bytes = smart_browz.screenshot_url(url, options)
            else:
                screenshot_bytes = smart_browz.screenshot_html(html_content, options)

            logger.info(
                "SmartBrowz screenshot: %dx%d → %d bytes",
                width,
                height,
                len(screenshot_bytes),
            )
            return screenshot_bytes if screenshot_bytes else b""
        except Exception as exc:
            logger.error("SmartBrowz generate_screenshot failed: %s", exc)
            raise CatalystServiceError(f"SmartBrowz screenshot failed: {exc}") from exc

    # ── Convenience: report-specific helpers ──────────────────────────────

    def generate_case_report_pdf(self, html_content: str) -> bytes:
        """Generate a case investigation report PDF with KSP letterhead."""
        return self.generate_pdf(
            html_content,
            {"format": "A4", "orientation": "portrait"},
            include_ksp_letterhead=True,
        )

    def generate_evidence_bundle_pdf(self, html_content: str) -> bytes:
        """Generate an evidence bundle PDF."""
        return self.generate_pdf(
            html_content,
            {"format": "A4", "orientation": "portrait"},
            include_ksp_letterhead=True,
        )

    def generate_analytics_chart_image(self, html_content: str) -> bytes:
        """Render an analytics chart (ECharts/Chart.js HTML) as a PNG image."""
        return self.generate_screenshot(
            html_content=html_content,
            width=1200,
            height=600,
            full_page=False,
        )

    # ── Health ─────────────────────────────────────────────────────────────

    def health_check(self) -> Dict[str, Any]:
        """Return wrapper health status."""
        available = is_catalyst_available()
        return {
            "service": "catalyst_smartbrowz",
            "available": available,
            "status": "ok" if available else "unconfigured",
            "features": {
                "pdf_generation": True,
                "screenshot": True,
                "ksp_letterhead": True,
            },
        }
